pipeline{
    agent any 
    tools {nodejs "NODEJS"}
    environment {
        AWS_ACCOUNT_ID = "448926670056"
        REGION = "us-east-1"
        DOCKER_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com"
        AWS_ECR_JENKINS_ACCESS = credentials('ECR_AWS_JENKINS_ACCESS')
        APP_NAME = "react-app-paps"
        DOCKER_REPOSITORY_NAME = "reactdocker"
        DOCKER_IMAGE_TAG = "latest"
    }
    stages{
        stage("cheking npm version"){
            steps{
                sh "npm version"
            }
        }
        stage("install dependencies"){
            steps{
                sh "npm install"
            }
        }
        stage("Test the testing files"){
            steps{
                sh "npm test"
            }
        }
        stage("build app"){
            steps{
                sh "npm run build"
            }
        }
        stage("deploy"){
            steps{
                script{
                    docker.withRegistry(
                    "https://${DOCKER_REGISTRY}",
                    "ecr:${REGION}:${AWS_ECR_JENKINS_ACCESS}"){
                        def myImage = docker.build("${DOCKER_REPOSITORY_NAME}")
                        myImage.push("${DOCKER_IMAGE_TAG}")
                    }
                }
            }
        }
    }
}