pipeline{
    agent any 
    tools {node 'NODEJS'}
    stages{
        stage("cheking npm version"){
            steps{
                sh "npm version"
            }
        }
        stage('install dependencies'){
            steps{
                sh 'npm install'
            }
        }
        stage('Test the testing files'){
            steps{
                sh 'npm test'
            }
        }
    }
}